# Generated by Django 4.0 on 2022-03-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
