# Generated by Django 4.0 on 2022-02-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='invitation1',
        ),
        migrations.RemoveField(
            model_name='group',
            name='invitation2',
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation1', models.BooleanField(default=False)),
                ('invitation2', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_group', to='capstone.group')),
            ],
        ),
    ]
