# Generated by Django 4.0 on 2022-02-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_remove_group_invitation1_remove_group_invitation2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='theme',
        ),
        migrations.AddField(
            model_name='invitation',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invitation',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
