# Generated by Django 4.0 on 2022-02-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_remove_group_description_remove_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='theme',
            field=models.CharField(max_length=150),
        ),
    ]
