# Generated by Django 4.0 on 2022-03-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_alter_groupdetails_user1_alter_groupdetails_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdetails',
            name='user1',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_user1', to='capstone.user'),
        ),
        migrations.AlterField(
            model_name='groupdetails',
            name='user2',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_user2', to='capstone.user'),
        ),
    ]
