# Generated by Django 4.0 on 2022-02-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_alter_invitation_name_alter_invitation_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='theme',
        ),
    ]
