# Generated by Django 4.0 on 2022-02-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_remove_invitation_description_remove_invitation_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='group_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='invitation_group_details', to='capstone.groupdetails'),
            preserve_default=False,
        ),
    ]
