# Generated by Django 4.0 on 2022-02-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_groupdetails_invitation_group_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='group_details',
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='inviting_user', to='capstone.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_user1', to='capstone.user'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_user2', to='capstone.user'),
        ),
        migrations.CreateModel(
            name='CreateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creategroup_group', to='capstone.group')),
                ('group_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creategroup_groupdetails', to='capstone.groupdetails')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creategroup_invitation', to='capstone.invitation')),
            ],
        ),
    ]
