# Generated by Django 4.0 on 2022-02-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_added',
            new_name='date',
        ),
    ]
