# Generated by Django 4.0 on 2022-02-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_alter_message_options_rename_date_added_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
        ),
    ]
