# Generated by Django 4.0 on 2022-02-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_user_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='price',
        ),
        migrations.AddField(
            model_name='coins',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
        ),
    ]
