# Generated by Django 4.0 on 2022-02-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_thread_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set(),
        ),
    ]
