# Generated by Django 4.0 on 2022-02-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0014_notification_alter_thread_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
